тз 10 первая сдача
moratti72r/java-filmorate pull request #3
Opened 2023-02-02 02:59 UTC by moratti72r

2023-02-02 19:59 UTC, Donald522 requested changes
Привет!

Структурно все верно.
Основное замечание по работе с хранилищем. Работа с данными должна происходить на его стороне. Неправильно на каждых чих делать findAll и что-то в них искать.

Поправь это и пойдем прикручивать базу.

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Контроллер не должен ходить напрямую в storage

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, InMemoryFilmStorage filmStorage) {
Можно использовать аннотацию ломбока @RequiredArgsContructor
Есть контруктор в классе единственный, то спрингу не требуется помечать его Autowired

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Integer> like = new HashSet<>();
Лучше в классе Film хранить только кол-во лайков числом
А в классе User хранить все фильмы, которые лайкнул конкретный пользователь

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger("FilmService.class");
Можно заменить на аннотацию `@Slf4j`

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.findAll().containsKey(idUser)) {
Правильнее было бы не вытаскивать все хранилище в сервис и делать проверку, а передать в storage идентификатор и спросить о его наличии
В виде интерфейса примерно так:
`boolean contains = userStorage.contains(userId)`

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.findAll().get(idFilm).getLike().add(idUser);
И здесь тоже, не нужно выкачивать все данные в сервис

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return filmService.getMostPopularFilms(0);
Не надо это делать через 0. Такая логика крайне неинтуитивна.
Если null - то передаем 10. Внутри сервиса не должно быть условий и логики про значение count. Он работает с тем, что ему передали.

Валидация параметра происходит в контроллере.
У аннотации `@RequestParam` есть возможность задать значение по умолчанию.

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.findAll().isEmpty()) {
Тут тоже самое замечание - эта логика должна быть на стороне хранилища.
Хранилище, в общем случае, не располагается в памяти приложения и достать оттуда данные - крайне дорогая операция. Нет смысла доставать 1000 записей, отсортировать их, чтобы потом 990 из них выбросить.

Вся эта логика должна быть на стороне хранилища.

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmAndUserExceptionHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Некорректные аргументы - это, скорее, 400 ошибка.

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.findAll().get(idUser).getFriends().contains(idFriend)) {
Здесь возможно NPE в момент `get(idUser).getFriends()`

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                allFriends.add(userStorage.findAll().get(idFriends));
У storage должен быть интерфейсный метод поиска по id

upd. Тем более он у тебя даже есть

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            log.info("Получен GET запрос");
От лога в таком виде пользы мало. Лог всегда должен иметь в себе id, чтобы по логу можно было отследить выполнение программы

2023-02-02 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
Это логика сервиса
в библиотеке StringUtils есть метод isBlank

2023-02-03 18:11 UTC, Donald522 requested changes
Привет!

Еще немного надо доделать.

2023-02-03 18:11 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().create(film);
Так это по сути тоже самое, что и было.
Контроллер вызывает методы репозитория

2023-02-03 18:11 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getSortFilms().stream().limit(count).collect(Collectors.toList());
Лимитирование тоже надо перенести в storage
Должен быть такой интерфейс в storage: `getTopFilms(int limit)`

2023-02-03 18:11 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getById(idFilm).setLikes(filmStorage.getById(idFilm).getLikes() + 1);
2 вызова storage тут не нужно делать.
Сначала делаем getById, потом все операции совершаем над локальной переменной.

Тут еще надо проверить, что этот пользователь уже не лайкал этот фильм. То есть сначала добавляем id фильма в лайки пользователя и, если успешно добавился, то инкрементируем счетчик лайков.

2023-02-03 18:11 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (StringUtils.isEmpty(user.getName())) {
Все таки эту логику надо перенести в UserService

2023-02-03 18:11 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new FilmNotFoundException("Список для сортировки не должен быть пустым");
Я бы не сказал, что отсутствие фильмов - это ошибка. Вернуть пустой список в данной ситуации корректно.

2023-02-03 21:20 UTC, moratti72r commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().create(film);
Про дублировал методы получения данных из классов хранилищ в классы сервисы. Если этот вариант не подходит, остается только наследоваться от хранилища...

2023-02-04 19:45 UTC, Donald522 requested changes
Привет!

-Добавление лайка к фильму сейчас некорректно работает. Надо проверять успешность добавления в set понравившихся фильмов пользователя-

2023-02-04 19:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        idGenerator++;
Эта логика должна была остаться в классе хранилища, а здесь его надо было вызвать.
Делать getAll при каждом добавлении нового фильма нельзя

2023-02-04 19:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setLikes(film.getLikes() + 1);
Ну поменять порядок вызовов тут не достаточно.
Ты не проверяешь успешность добавления в user.getLikes

Почитай описание метода add в интерфейсе Set

2023-02-04 19:45 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        idGenerator++;
Строки 80-82 в storage

2023-02-04 20:30 UTC, Donald522 approved these changes

2023-02-05 16:38 UTC, Donald522 approved these changes

2023-02-14 08:46 UTC, merged