Add database
moratti72r/java-filmorate pull request #4
Opened 2023-04-27 19:34 UTC by moratti72r

2023-04-28 20:06 UTC, Donald522 requested changes
Привет!

Надо немного схему БД поправить и запросы.

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/genres")
Это лучше в отдельные контроллеры вынести и вернуть /films на уровень класса

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            String sq = "SELECT * FROM genres WHERE id_genre IN " +
Ходить в базу из маппера не надо. 
Маппер это конвертер

Второе, все данные для построения объекта Film надо доставать одним запросом

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        int idFilm = jdbcTemplate.queryForObject("SELECT id_film FROM films WHERE name_film = ?", Integer.class, film.getName());
Посмотри на GeneratedKeyHolder. Доставать id отдельным запросом не надо

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("select * from films where id_film = ?", id);
Для проверки наличия можно select 1 сделать. Незачем тащить данные по сети, если их не использовать

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            String sq = "SELECT * FROM genres WHERE id_genre IN " +
Надо одним запросом все доставать. Используй join-ы

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            String sqFriends = "SELECT id_friend FROM friends WHERE id_user=?";
Тоже самое, надо одним запросом

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        if (contains(id)) {
А зачем делать предварительный запрос на проверку наличия? 
Почему нельзя сделать сразу запрос ниже?

2023-04-28 20:06 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genres.java
> +    public int hashCode() {
А чего не ломбок?

2023-04-28 20:06 UTC, Donald522 commented on src/main/resources/schema.sql
> +    id_film      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
постфикс film я бы убрал. Просто id, name

2023-04-28 20:06 UTC, Donald522 commented on src/main/resources/schema.sql
> +    id_genre   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Тут тоже названия просто id, name.
По имени таблицы понятно к чему это относится

2023-04-28 20:06 UTC, Donald522 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS films_genres
Какой ключ в таблице?

2023-04-28 20:06 UTC, Donald522 commented on src/main/resources/schema.sql
> +    login    varchar NOT NULL,
На логин советую сделать ограничение unique

2023-05-01 10:34 UTC, TyutterinYakov reviewed
Добрый день! В целом - хорошо) Отметил то, что следует исправить) Хорошего дня! Если возникнут вопросы -пиши в пачку, буду рад помочь🌞

2023-05-01 10:34 UTC, TyutterinYakov commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
На данном этапе мы работаем с `JDBC`, следует использовать соответствующую зависимость)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/genres")
Для работы с жанрами и рейтингами следует ввести отдельные контроллеры, так как функционал приложения может расти и следовательно потом будет не очень легко сопровождать классы с большим числом строк кода) А также, таким образом, мы будем соблюдать принцип единственной ответственности класса

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
Следует реализовать функционал)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
Следует реализовать функционал)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
Для соблюдения инкапсуляции - поля класса должны быть приватными)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
В данном случае для проверки значения поля `name` следует использовать `@NotBlank`, так как `@NotEmpty` примет строку, состоящую только из пробелов - за корректную)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
Аннотация `@NotNull` не используется над примитивами - следует исключить ее над полем `duration`

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    MPA mpa;
Так как фильмов без рейтинга не может быть в нашей системе - следует над этим полем навесить аннотацию `@NotNull`

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      int likes;
Так как значение `likes` не передается от пользователя и используется лишь внутри нашей системы, хорошо было бы навесить над полем - `@JsonIgnore`, чтобы оно не учитывалось при сериализации-десериализации)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/exception/MPANotFoundException.java
> +    String message;
Для соблюдения инкапсуляции - поля класса должны быть приватными)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/exception/GenreNotFoundException.java
> +        String message;
Для соблюдения инкапсуляции - поля класса должны быть приватными)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/exception/GenreNotFoundException.java
Можно не делать столько отдельных исключений notFound. В больших проектах сущностей может быть сотни, не делать же под каждую отдельное исключение. Можно объявить одно общее EntityNotFoundException и передавать для информативности в его конструктор класс объекта сущности

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/exception/MPANotFoundException.java
Можно не делать столько отдельных исключений notFound. В больших проектах сущностей может быть сотни, не делать же под каждую отдельное исключение. Можно объявить одно общее EntityNotFoundException и передавать для информативности в его конструктор класс объекта сущности

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmAndUserExceptionHandler.java
В класс следует добавить логирование) Для этого достаточно использовать аннотацию из lombok ->> `@Slf4j`. Далее в каждый наш хендлер следует добавить логирование сообщения об ошибке)
Так же следует добавить хендлер для обработки всех необработанных исключений, ловить будем `Throwable`, а возвращать статус 500 INTERNAL_SERVER_ERROR
Так же следует добавить обработчик для исключения, которое выбрасывается при валидации данных с помощью аннотаций - `MethodArgumentNotValidException`, возвращать будет статус 400 BAD_REQUEST, так как ошибка связана с некорректными данными от пользователя)
акже хорошо было бы передать в лог сообщение об ошибке, а можно и весь трейс, чтобы в случае ошибки было проще разобраться, что именно произошло)
Кстати, при логгировании более эффективно использовать не конкатенацию, а заполнитель - placeholder `{}`
Например:
`log.debug("Получен статус 404 Not found {}", ex.getMessage(), ex);`
Аналогично в других местах)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private Set<Integer> friends = new HashSet<>();
Коллекция идентификаторов друзей более не требуется, так как теперь хранение осуществляется в БД, а для их получения присутствует отдельный эндпоинт)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> likesOnMovies = new HashSet<>();
Аналогично, эту коллекцию также следует исключить

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
Для валидации почты следует использовать `@Email` в связке с `@NotEmpty`, так как `@Email` допускает `null` и пустую строку за корректное значение)

Для даты рождения хорошо было бы использовать `@PastOrPresent`, так как эта аннотация допускает не только дату из прошлого, но и равную текущей) Также не забываем использовать `@NotNull`, так как текущая и эта допускают `null` за корректное значение)


(предложение) Так как строка с логином не может быть `null` и состоять только из пробелов, хорошо было бы использовать аннотацию `@NotBlank`. Также строка не может содержать пробелов - для этой цели было бы удобно использовать аннотацию `@Pattern`
https://www.geeksforgeeks.org/spring-mvc-regular-expression-validation/

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    public List<Genres> getAllGenres();
Указание модификаторов доступа у методов в интерфейсах - не требуется, так как они в любом случае должны быть публичными в классе, который реализует интерфейс)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
Эта реализация более не будет использоваться, следует ее исключить, так как она будет лишь мешать при добавлении нового функционала)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
Эта реализация более не будет использоваться, следует ее исключить, так как она будет лишь мешать при добавлении нового функционала)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryMPAStorage.java
Эта реализация более не будет использоваться, следует ее исключить, так как она будет лишь мешать при добавлении нового функционала)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryGenreStorage.java
Эта реализация более не будет использоваться, следует ее исключить, так как она будет лишь мешать при добавлении нового функционала)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +    id_genre   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Также следует подправить)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +    id_film      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Также следует подправить)

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS likes
Первичный ключ в связующей таблице должен выступать в виде отдельного столбца, либо же быть составным, например, `PRIMARY KEY (user_id,film_id)`

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS friends
Первичный ключ в связующей таблице должен выступать в виде отдельного столбца, либо же быть составным

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS films_genres
Первичный ключ в связующей таблице должен выступать в виде отдельного столбца, либо же быть составным

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS mov_users
Можно было бы ввести ограничение на уникальность логина и почты на уровне таблицы в БД)
```
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);
```

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private RowMapper<Film> filmRowMapper() {
Хорошо было бы придерживаться порядка во всех классах и сначала располагать публичные методы(предоставляемый API), а затем уже приватные - внутренняя реализация). Таким образом будет проще извлекать информацию из кода и ориентироваться по нему

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
Для работы с жанрами, рейтингами, лайками - следует ввести другие DAO, так как это отдельные сущности в БД

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
Для работы с друзьями - следует ввести другое DAO, так как это отдельная сущность в БД

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    public User create(User user) {
В данном случае следует использовать `KeyHolder`, чтобы не производить дополнительное обращение к БД для получения установленного идентификатора)
https://stackoverflow.com/questions/17771306/spring-how-to-use-keyholder-with-postgresql

2023-05-01 10:34 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public Film create(Film film) {
В данном случае следует использовать `KeyHolder`, чтобы не производить дополнительное обращение к БД для получения установленного идентификатора)
https://stackoverflow.com/questions/17771306/spring-how-to-use-keyholder-with-postgresql

2023-05-03 18:09 UTC, closed without merging